#!/bin/sh

if [ "$#" -ne 1 ]; then
    echo "Usage: kp <port-number>"
    exit 1
fi

PORT=$1

PID=$(lsof -ti tcp:$PORT)

if [ -z "$PID" ]; then
    echo "No process found running on port $PORT."
    exit 1
else
    kill -9 $PID
    echo "Killed process $PID running on port $PORT."
fi
